services:
  garagio:
    image: ghcr.io/parallelo3301/garagio:latest
    ports:
      - '${PORT:-8000}:${PORT:-8000}'
    env_file:
      - .env
    environment:
      DENO_SQLITE_PATH: /usr/local/lib/libsqlite3.so
    volumes:
      - ./data:/data
    restart: unless-stopped
