// This file is generated by `deno task dev` and kept explicit for compiled builds.
import * as $0 from './routes/_app.tsx';
import * as $1 from './routes/index.tsx';
import * as $2 from './routes/api/items/index.ts';
import * as $3 from './routes/api/items/[id].ts';
import * as $4 from './routes/api/manufacturers/index.ts';
import * as $5 from './routes/api/wiki/index.ts';
import * as $6 from './routes/api/wiki/[id].ts';
import * as $7 from './routes/api/manufacturers/[id].ts';
import * as $$0 from './islands/InventoryApp.tsx';

const manifest = {
  routes: {
    './routes/_app.tsx': $0,
    './routes/index.tsx': $1,
    './routes/api/items/index.ts': $2,
    './routes/api/items/[id].ts': $3,
    './routes/api/manufacturers/index.ts': $4,
    './routes/api/wiki/index.ts': $5,
    './routes/api/wiki/[id].ts': $6,
    './routes/api/manufacturers/[id].ts': $7,
  },
  islands: {
    './islands/InventoryApp.tsx': $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;