// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from './routes/_app.tsx';
import * as $_middleware from './routes/_middleware.ts';
import * as $api_auth_login from './routes/api/auth/login.ts';
import * as $api_auth_logout from './routes/api/auth/logout.ts';
import * as $api_items_id_ from './routes/api/items/[id].ts';
import * as $api_items_index from './routes/api/items/index.ts';
import * as $api_manufacturers_id_ from './routes/api/manufacturers/[id].ts';
import * as $api_manufacturers_index from './routes/api/manufacturers/index.ts';
import * as $api_uploads_index from './routes/api/uploads/index.ts';
import * as $api_wiki_id_ from './routes/api/wiki/[id].ts';
import * as $api_wiki_index from './routes/api/wiki/index.ts';
import * as $index from './routes/index.tsx';
import * as $uploads_file_ from './routes/uploads/[file].ts';
import * as $InventoryApp from './islands/InventoryApp.tsx';
import type { Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/_app.tsx': $_app,
    './routes/_middleware.ts': $_middleware,
    './routes/api/auth/login.ts': $api_auth_login,
    './routes/api/auth/logout.ts': $api_auth_logout,
    './routes/api/items/[id].ts': $api_items_id_,
    './routes/api/items/index.ts': $api_items_index,
    './routes/api/manufacturers/[id].ts': $api_manufacturers_id_,
    './routes/api/manufacturers/index.ts': $api_manufacturers_index,
    './routes/api/uploads/index.ts': $api_uploads_index,
    './routes/api/wiki/[id].ts': $api_wiki_id_,
    './routes/api/wiki/index.ts': $api_wiki_index,
    './routes/index.tsx': $index,
    './routes/uploads/[file].ts': $uploads_file_,
  },
  islands: {
    './islands/InventoryApp.tsx': $InventoryApp,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
