// This file is generated by `deno task dev` and kept explicit for compiled builds.
import * as $0 from './routes/_app.tsx';
import * as $1 from './routes/index.tsx';

const manifest = {
  routes: {
    './routes/_app.tsx': $0,
    './routes/index.tsx': $1,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;